### ISSUE TITLE
Enable the new attachments feature. 

### ISSUE THREAD

**Issue by BenjaminMcC** [briandconnelly/pushoverr#8]
Hi, Release 3.1 of pushoverr added a feature for attachments to be sent: 

https://pushover.net/clients/changelog

**Comment by yanlesin** [comment]
Hi @briandconnelly, I implemented support for image attachments as separate function and ggpushover function to push ggplot plots in notifications. Please let me know, if you will consider pull request for this to enhance functionality of your package.
